### PR TITLE
Fix some unused parameter warnings.

### PR DESCRIPTION
**Pull request by jeremy-murphy**
Hi! Sorry, I know very little about your library but I assume these are just unused parameters that have missed your attention. I ran the tests and they all passed. Cheers.

### CODE REVIEW

**Comment by timblechmann** [comment]
looks good, thanks a lot!

**Comment by Lastique** [comment]
I'd rather disable such warnings with a pragma in the future. Parameter names serve documentation purpose, even if not used.

**Comment by jeremy-murphy** [comment]
Ah, OK, what's the portable way to do that? With an actual `#pragma` or `BOOST_ATTRIBUTE_UNUSED`?

**Comment by Lastique** [comment]
I don't think `BOOST_ATTRIBUTE_UNUSED` has any effect on MSVC. So yes, I meant the actual `#pragma`, and since every compiler has its own set of warnings and ways to disable them, this would not be quite portable. Still, the effect can be achieved on most popular compilers. From my experience, it's best to introduce prefix and postfix headers that disable/restore offending warnings and include those headers at the beginning and the end of every other header of the library. I guess I'll have to introduce such headers for Boost.Atomic.

**Pull request merged**
